# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180410_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
