# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180411_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_korp_kontrol',
            name='informaciaya_o_gosah_s_saitov_raskritiya_informacii',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='data_korp_kontrol',
            name='polucheno_1_2_bool',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='data_korp_kontrol',
            name='polucheno_1_3_bool',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='data_korp_kontrol',
            name='predpisanie_ob_istrebovanii_documentov',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='data_korp_kontrol',
            name='predpisanie_ob_istrebovanii_documentov_3_3',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='data_korp_kontrol',
            name='prepsanie_ob_ustranenii_narusheniya_zakonodatelstva_RF',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='data_korp_kontrol',
            name='zapros_o_predostavlenii_informacii',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='data_korp_kontrol',
            name='zapros_o_predostavlenii_informacii_3_2',
            field=models.NullBooleanField(default=False),
        ),
    ]
