# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('object_id', models.IntegerField(blank=True, db_column='object_id')),
                ('datetime', models.DateTimeField(db_column='datetime')),
                ('type_id', models.IntegerField(blank=True, db_column='content_type_id')),
                ('user_id', models.IntegerField(blank=True, db_column='user_id')),
            ],
            options={
                'db_table': 'easyaudit_crudevent',
                'managed': False,
            },
        ),
    ]
