# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 17:13
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=app.models.path_and_rename),
        ),
    ]
